### ISSUE TITLE
问个vim相关的问题

### ISSUE THREAD

**Issue by cykuo3** [nine2/b-vim#1]
请问大佬，我作为一个javaer，也是一个轻度的vim使用者。但是一直当作文本编辑器来用。请问，用vim写java好实现么

**Comment by bbxytl** [comment]
好实现，要装ycm，项目里有java.vim的文件配置

**Comment by bbxytl** [comment]
Ycm支持java补全，也可以使用vim-coc来处理补全，coc也支持java补全https://github.com/neoclide/coc-java
